"""Initial setting

Revision ID: 601ff497fa96
Revises:
Create Date: 2023-05-21 18:42:57.629402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601ff497fa96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('item',
                    sa.Column('item_id', sa.String(length=256), nullable=False),
                    sa.Column('category', sa.String(length=256), nullable=False),
                    sa.Column('callname', sa.String(length=256), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.Column('description', sa.String(length=256), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('image_url', sa.String(length=1024), nullable=True),
                    sa.PrimaryKeyConstraint('item_id'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=256), nullable=True),
                    sa.Column('surname', sa.String(length=256), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('recipe',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('label', sa.String(length=256), nullable=False),
                    sa.Column('url', sa.String(length=256), nullable=True),
                    sa.Column('source', sa.String(length=256), nullable=True),
                    sa.Column('submitter_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['submitter_id'],
                        ['user.id'],
                    ),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_recipe_id'), 'recipe', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_url'), 'recipe', ['url'], unique=False)
    # ### end Alembic commands ###s


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_url'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_id'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('item')
    # ### end Alembic commands ###
